project:
  type: website
  
execute:
  freeze: auto

website:
  page-navigation: true
  title: "MATH 2025 - Fall 2025"
  description: "Homepage for MATH 2025 - Multiple Regression Analysis at the College of Idaho, Fall 2025"
  site-url: https://math2025fa25.netlify.app/
  
  repo-url: https://github.com/MATH2025FA25/MATH2025FA25
  repo-actions: [edit, issue]
  
  page-footer:
    background: "#412d5e"
    left: |
      &copy; Copyright 2025, Eric Friedlander
    right: |
      This site is built with [Quarto](https://quarto.org/)
      
  sidebar:
    background: "#bbbbbb"
    logo: "images/logo.png"
    align: center
    tools: 
      - icon: code-square
        href: https://rstudio.collegeofidaho.edu/
        text: "RStudio"
      - icon: person
        href: https://cofi.instructure.com/courses/17093
        text: "Canvas"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - schedule.qmd
      - syllabus.qmd
      - support.qmd
      - links.qmd
      - section: Computing
        contents: 
        - href: computing-access.qmd
        - href: computing-inferencesummary.qmd
        - href: computing-r-resources.qmd
          text: R resources
      - section: Project
        contents:
        - href: project/project-instructions.qmd
          text: "Instructions"
        - href: project/project-rubric.qmd
          text: "Supplementary Report Rubric"
        - href: project/poster-rubric.qmd
          text: "Poster Rubric"
      - section: Exams
        contents:
        - href: exam/exam-rubric.qmd
          text: "Oral Exam Rubric"
        - href: exam/exam-01-review.qmd
          text: "Exam 1 Overview"
        - href: exam/exam-01-practice.qmd
          text: "Exam 1 Practice"
        - href: exam/exam-02-review.qmd
          text: "Exam 2 Overview"
        - href: exam/exam-02-practice.qmd
          text: "Exam 2 Practice"
        
  
 
format:
  html:
    theme:
      - cosmo
      - theme.scss
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: true
    



