---
title: "Exam 02 review"
author: "Prof. Eric Friedlander"
footer: "[🔗 MATH 2025 - Fall 2025 - Schedule](https://math2025fa25.netlify.app/schedule)"
logo: "../images/logo.png"
format: 
  revealjs:
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: false
    incremental: false 
    chalkboard: true
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
  cache: false
knitr:
  opts_chunk: 
    R.options:      
    width: 200
---


## Exam 02 {.midi}

-   20% of final course grade

-   In-class: 75 minutes during Wed, Dec 3

## Content {.midi}

:::: columns
::: {.column width="50%"}
-   Cumulative with a focus on material since Exam 01

-   All content from Exam 01 plus:


-   Fitting, interpreting, comparing, and evaluating multiple linear regression models

-   Transformations

-   Outliers
:::

::: {.column width="50%"}
-   Multiple Linear regression

-   Categorical Variables

-   Interaction Terms

-   Conditions

-   Multicollinearity

-   Model Comparison
:::
::::

## Outline of in-class portion {.midi}

-   Closed-book, one sheet of handwritten notes (front and back)

-   Question types:

    -   Multiple choice
    -   Short answer (no more than 3 sentences)
    -   True/ False.
        -   If false, write 1 - 2 sentence justification about why it is false. Must get justification correct to receive credit.
    -   Evaluate a response.
    -   Long answer

-   Last page will have analysis output.

-   Just need a pencil or pen. No calculator permitted on exam.

## Format {.midi}

-   Five types of questions (potentially divided into sections)
    -   Multiple choice (concepts, interpretation)
    -   Short answer (concise reasoning, set up calculations)
    -   True/False with justification (1–2 sentences)
    -   Evaluate a response (diagnose a student’s statement)
    -   Long answer (explanation and interpretation)
-   Emphasis on interpretation and understanding
-   You will not write code; you may be asked to interpret provided output

# Practice

::: appex
📋 Exam 2 Practice: [ae-19-Exam2-practice](../ae/ae-19-Exam2-practice.pdf)
:::

