---
title: Exam Rubric
---



The is an oral exam designed to last 50 minutes. You will be asked a combination of questions requiring both R and a conceptual understanding of the material. At the end of 50 minutes we will spend 10 minutes jointly deciding your grade using the following rubric as a guide:

- 100: Student demonstrates complete understanding of the material including the ability to synthesize and extend the material from this course. There are no conceptual mistakes and any coding mistakes are complete superficial. You have truly impressed Dr. F.
- 95: Student demonstrates complete understanding of the material including the ability to synthesize the material from this course and is able to extend the material with minimal prompting from the instructor. Any mistakes are minor and infrequent. The student requires only minimal help with coding, for example pointing out missing comma's.
- 90: Student demonstrates that they know and understand all or almost all of the content but without true synthesis. Basic questions come to this students easily. The student is able to answer questions of moderate difficulty with some trouble but no help. However, the student struggles to place the material from the course in context without prompting from the instructor or the student makes one major mistake or many minor mistakes. The student may require more than minimal help with coding, for example reminders about the names of functions.
- 85: Student has at least one minor gap in their understand of the material. They are able to answer most but not all problems without the help of the instructor and do not demonstrate the ability to synthesize and extend the course content. The student may take enough time on easier problems that we are unable to assess harder content. The student may require more than minimal help with coding, for example reminders about the names of functions.
- 80: Student has several minor gaps in their understanding of the material. They can answer some questions without help but frequently need prompting from the instructor. The student may take enough time on easier problems that we are unable to assess harder content. The student may require more than minimal help with coding, for example reminders about the names of functions.
- 75: Student has at least one major gap and/or many minor gaps in their understanding of the material. They can solve some problems without help but frequently need prompting from the instructor. The student does take enough time on easier problems that we are unable to assess harder content. The student may requires frequent help with coding but it is clear that they have been working through the homeworks and grasp some of the concepts.
- 70: Student has several major gaps in their understanding of the material. They can answer some problems without help but frequently need prompting from the instructor. Furthermore, there are some problems they don't know how to start. The student may requires frequent help with coding but it is clear that they have been working through the homeworks and grasp some of the concepts.
- 65: Student is familiar with the basic definitions in the course. Student can get through many questions but only with frequent help from the instructor. The student may requires frequent help with coding but it is clear that they have been working through the homeworks and grasp some of the concepts.
- 60: Student is familiar with the basic definitions in the course. The student may requires frequent help with coding but it is clear that they have been working through the homeworks and grasp some of the concepts.
- <60: If a grade below 60 is assigned, Dr. Friedlander will decide the grade that is earned based on the students knowledge of the material.
