{
  "hash": "6c874e812856755a910146bc7fd1e55c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Exam 1 Practice\"\nauthor: \"MATH 2025\"\nformat:\n  pdf:\n    pdf-engine: pdflatex\n    documentclass: exam\n    include-in-header:\n      - text: |\n          \\newcommand{\\E}{\\mathbb{E}}\n          \\newcommand{\\Var}{\\text{Var}}\n          \\newcommand{\\SD}{\\text{SD}}\n          \\newcommand{\\PP}{\\text{P}}\n          \\newcommand{\\bq}{\\begin{questions}}\n          \\newcommand{\\eq}{\\end{questions}}\n          \\newcommand{\\bp}{\\begin{parts}}\n          \\newcommand{\\ep}{\\end{parts}}\n          \\newcommand{\\bs}{\\begin{subparts}}\n          \\newcommand{\\es}{\\end{subparts}}\n---\n\n**Answer the questions in the spaces provided. Show your work wherever practicable. You are permitted to use a calculator but not any other resources.**\n \n\nThe data set for this exam is a subset from the Spotify Songs Tidy Tuesday data set. The data were originally obtained from Spotify using the **spotifyr** R package. **It is the same data set we used for our activities.**\n\nIt contains numerous characteristics for each song. This analysis will focus specifically on the following variables:\n\n| variable         | class     | description  |\n|:------------|:------------|:----------------------------------------------|\n| track_popularity | double    | Song Popularity (0-100) where higher is better |\n| energy           | double    | Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy. |\n| valence          | double    | A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).  |\n| danceability |\tdouble |\tDanceability describes how suitable a track is for dancing based on a combination of musical elements including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable. |\n| playlist_genre\t | character |\tThe genre of the song (`edm`, `latin`, `pop`, `r&b`, `rap`, `rock`)\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspotify |> \n  select(track_popularity, energy, valence, playlist_genre) |> \n  head() |> \n  kable()\n```\n\n::: {.cell-output-display}\n\n\n| track_popularity| energy| valence|playlist_genre |\n|----------------:|------:|-------:|:--------------|\n|               80|  0.859|   0.520|pop            |\n|               80|  0.694|   0.216|pop            |\n|               83|  0.777|   0.706|latin          |\n|               83|  0.499|   0.511|rap            |\n|               89|  0.892|   0.478|pop            |\n|               83|  0.880|   0.534|pop            |\n\n\n:::\n:::\n\n\n\\newpage\n\nFor questions 1-7, consider `model1` below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(danceability ~ valence + energy, data=spotify)\nmodel1 |> tidy() |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    0.643|     0.022|    29.694|   0.000|\n|valence     |    0.260|     0.027|     9.693|   0.000|\n|energy      |   -0.125|     0.037|    -3.410|   0.001|\n\n\n:::\n:::\n\n\n\\bq\n\n\\question[5] Use the values above to write down the equation that represents the regression model. Use the variable names to represent the variables rather than $Y$'s and $X$'s.\n\n\\vfill\n\n\\question[10] Give a one sentence interpretation (in context) of the first two numbers in the estimate column (i.e. 0.643 and 0.260).\n\n\\vfill\n\n\\newpage\n\n\\question[5] Which of the following represents the predicted `danceability` for a single observation that has a `valence` of 0.5 and an `energy` of 0.25?\n\n\\begin{choices}\n\\item $0.643 + 0.260 - 0.125 = 0.778$\n\\item $0.643 + 0.260\\times 0.5 - 0.125\\times 0.25 = 0.7418$\n\\item $29.694 + 9.693\\times 0.25 - 3.410\\times 0.5 = 30.4123$\n\\item $0.260\\times 0.25 - 0.125\\times 0.5 = 0.0025$\n\\item Not enough information\n\\end{choices}\n\n\\question[5] What is the residual of this estimated `danceability`?\n\n\\begin{choices}\n\\item $-0.240$\n\\item $0.143$\n\\item $0.375$  \n\\item Not enough information to say\n\\end{choices}\n\n\\question[5] Suppose you generate a 95% prediction interval for this prediction. If we change this prediction interval to a confidence interval (that is make a prediction for the average of your response rather than a single prediction) the width of the interval would:\n\n\\begin{choices}\n\\item increase\n\\item decrease\n\\item remain unchanged (approximately)\n\\end{choices}\n\n\n\n\\question[15] Suppose you use bootstrapping to generate a 95% confidence interval for the slope of `valence` in `model1`. For each of the following changes, indicate whether the width of your interval would increase, decrease, or approximately remain the same (keeping all else constant):\n\n\\bp\n\n\\item Increase sample size:\n\n\\begin{choices}\n\\item increase\n\\item decrease\n\\item remain unchanged (approximately)\n\\end{choices}\n\n\\item Increase confidence level:\n\n\\begin{choices}\n\\item increase\n\\item decrease\n\\item remain unchanged (approximately)\n\\end{choices}\n\n\\item Increase the number of bootstrapped replicates:\n\n\\begin{choices}\n\\item increase\n\\item decrease\n\\item remain unchanged (approximately)\n\\end{choices}\n\n\\ep\n\n\\newpage\n\n\\question[15] \nConsider a hypothesis test to determine whether there is a relationship between `valence` and `danceability` in `model1`:\n\n\\bp\n\n\\item State the null and alternative hypothesis in both words and symbols.\\vfill\n\\item Give a rough definition of a p-value in the context of this problem.\\vfill\n\\item What would be the result of the test in the context of the problem if $\\alpha = 0.05$?\\vfill\n\n\\ep\n\n\\newpage\n\nFor question 8, consider `model2` below:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- lm(danceability ~ valence + energy + playlist_genre, data=spotify)\n```\n:::\n\n\n\\question[5] Recall that `playlist_genre` has 6 distinct genre's. How many *additional* parameters (i.e. $\\beta$'s) would `model2` include that `model1` would not?\n\n\\begin{choices}\n\\item 5\n\\item 6\n\\item 10\n\\item 12\n\\item 15\n\\item 18\n\\end{choices}\n\n\\newpage \n<!-- \\question[5] Compared to `model1`, the $\\hat{\\beta}_i$'s corresponding to `valence` and `energy` would: -->\n\n<!-- \\begin{choices} -->\n<!-- \\item Increase -->\n<!-- \\item Decrease -->\n<!-- \\item Remain the same -->\n<!-- \\item Not enough information to say -->\n<!-- \\end{choices} -->\n\n\\question[10] For the constant variance assumption of a linear model, sketch a plot that would show that this assumption would be violated. Make sure to clearly label your axes so I know what the plot represents. Feel free to also describe what I should be looking for in words if you feel that your plot is not sufficiently clear.\\vfill\n\n\\newpage \n\nThe code below will be helpful for the rest of the exam.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nspotify <- spotify |> \n  mutate(pop_indicator = as.factor(ifelse(playlist_genre == \"pop\", \"pop\", \"not pop\")))\n```\n:::\n\n\n\n\\question[8]\n\nConsider the following model:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(danceability ~ energy*pop_indicator, data=spotify)\n\nmodel1 |> tidy() |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|term                    |   estimate| std.error| statistic|   p.value|\n|:-----------------------|----------:|---------:|---------:|---------:|\n|(Intercept)             |  0.6478241| 0.0312549| 20.727138| 0.0000000|\n|energy                  |  0.1053857| 0.0489308|  2.153772| 0.0317316|\n|pop_indicatorpop        |  0.0477146| 0.0464676|  1.026837| 0.3049900|\n|energy:pop_indicatorpop | -0.1266868| 0.0710332| -1.783487| 0.0751086|\n\n\n:::\n:::\n\n\nThis model contains two different lines. One for `pop` songs and one for `not pop`. Write down the equations of both lines. For partial credit you may just write down the equation of the model.\n\n\\bp\n\n\\item \\texttt{pop} line:\n\n\\vfill\n\n\\item \\texttt{not pop} line:\n\n\\vfill\n\n\\ep\n\n\\newpage\n\nFor questions 11-18, consider the following models:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel1 <- lm(danceability ~ energy*pop_indicator, \n             data=spotify)\nmodel2 <- lm(danceability ~ valence, data=spotify)\nmodel3 <- lm(danceability ~ valence + energy + pop_indicator, data=spotify)\nmodel4 <- lm(danceability ~ valence + track_popularity + energy*pop_indicator, data=spotify)\n```\n:::\n\n\n\\question[5] Which of the following metrics is the LEAST useful for comparing these four models:\n\n\\begin{choices}\n\\item $R^2$\n\\item $R^2_{adj}$\n\\item AIC\n\\item BIC\n\\item $C_p$\n\\end{choices}\n\n\\question[5] For the answer you selected above, which of the following is true (select all that apply):\n\n\\begin{choices}\n\\item It is fine to use for comparing models with the same number of parameters.\n\\item Using it can lead to overfitting because increasing the model complexity will always lead to a ``better'' number.\n\\item We only use it when we are looking at a model with one predictor.\n\\item Even though it isn't useful for comparing models of different sizes, it is useful for describing a model's quality once a model is chosen.\n\\item It penalizes models for being more complex.\n\\end{choices}\n\n\\question[6] Which of the following models are nested in one another (select all that apply):\n\n\\begin{choices}\n\\item model1 in model2\n\\item model1 in model3\n\\item model1 in model4\n\\item model2 in model3\n\\item model2 in model4\n\\item model3 in model4\n\\end{choices}\n\n\\newpage\n\nFor questions 14 - 18 consider the following output in addition to the code at the beginning of the previous page:\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|Model  | r.squared| adj.r.squared|      AIC|      BIC|\n|:------|---------:|-------------:|--------:|--------:|\n|model1 |     0.023|         0.017| -623.009| -601.857|\n|model2 |     0.139|         0.137| -691.201| -678.509|\n|model3 |     0.169|         0.164| -705.188| -684.035|\n|model4 |     0.174|         0.166| -704.189| -674.576|\n\n\n:::\n:::\n\n\n\\question[2] Which model is \"best\" according to $R^2$?\n\n\\begin{choices}\n\\item model1\n\\item model2\n\\item model3\n\\item model4\n\\end{choices}\n\n\\question[2] Which model is \"best\" according to $R^2_{adj}$?\n\n\\begin{choices}\n\\item model1\n\\item model2\n\\item model3\n\\item model4\n\\end{choices}\n\n\\question[2] Which model is \"best\" according to AIC?\n\n\\begin{choices}\n\\item model1\n\\item model2\n\\item model3\n\\item model4\n\\end{choices}\n\n\\question[2] Which model is \"best\" according to BIC?\n\n\\begin{choices}\n\\item model1\n\\item model2\n\\item model3\n\\item model4\n\\end{choices}\n\n\\question[3] Which model do you think is \"best\"? If there are two candidate models select the one which is more \"parsimonious\"? Very briefly state your rationale.\n\n\\begin{choices}\n\\item model1\n\\item model2\n\\item model3\n\\item model4\n\\end{choices}\n\n\n\\eq\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}