---
title: "Self and Peer Review"
editor: 
  markdown: 
    wrap: 72
---

> Writing without revising is the literary equivalent of waltzing gaily out of the house in your underwear. ― Patricia Fuller

## Anecdote you can skip if you want

I'd like to take a minute and explain why I place so much emphasis on writing and communication.
When I was a graduate student and I turned in my first draft of my very first paper to my advisor, it was bad... Like WAAAAAY BAD. My advisor was a wonderful and kind gentleman and he didn't want to be mean so instead of just putting a big red X through everything that I wrote, he crossed out all of the word individually except for words like "the", "and", "but", etc. as if he was just making small changes to the wording of what I had wrote. However, I got the message and started putting a lot more effort into my writing. It was hard. My undergraduate was at an engineering school where all of my homeworks had "right" or "wrong" answers. I think I only wrote three essays during my entire college career and it showed. This is why I place so much emphasis on you being able to write and communicate your thoughts in a way that (a) makes it easy for other people to understand and (b) makes it clear that you know what you're talking about.

## Introduction

This document addresses Stages IV (Peer Review) and V (Project Revision) of your MAT-212 final project.
The purpose of this exercise is to teach you how to improve your writing. The best way I have found to improve my writing is to just stop, reread, and mercilessly delete and rewrite. 
Entire paragraphs may move or disappear. 
The second purpose of this exercise is to show you (a little bit) how academic peer review works. In a professional publication, reviewers critique your writing/explanation and your method. Here, peer reviewers will focus just on critiquing of writing/explanation; your professor will comment on method.
The process of writing and responding to comments in a separate document mimics how the review process works for professional publications.

## Stage IV: Peer review

> The first draft of anything is shit. ― Ernest Hemingway

Each person will have one manuscript to read. The purpose of the peer-review is to identify areas of the paper in which communication of statistical ideas needs to be improved. You may also offer suggestions for additional statistical analysis or ideas for future research, but it is not your goal to critique or criticize the analyses that have already been completed (the professor will provide guidance in this aspect). As a reviewer, it is NOT your job to correct spelling or grammatical mistakes. It is also NOT your job to offer precise rewording of sentences or phrases, just to point out where such rephrasing could occur. Your feedback will be provided to the author in a separate typed document.
For your assigned manuscript, follow this procedure:

0.  You will be assigned a manuscript to peer review through the Stage III assignment on Canvas.
1.	Read the manuscript, noting confusing things (underline, circle, write notes in the margins, etc.). On the first read-through, focus on getting the MAIN IDEA of the paper.  
2.	Re-read the manuscript. Now specifically focus on the confusing parts, and see if you can figure them out. Maybe the author needs to explain things in a better order? or use less jargon? Is the writing style professional, concise, precise, and understandable? Write down these comments. 
3.	Re-read, focusing on each section of the paper (the ["Revising Guide"](https://cofi.instructure.com/courses/15692/assignments/200729) will probably help here). Does it include the necessary items listed in the [Project Report Section of the project instruction](project-instructions.qmd#draft-report)? Are all things in the correct sections? Is all relevant information provided? 
4.	Are figures/graphs/tables well-labeled and understandable? 
5.	Summarize your comments in a typed document using the ["Revising Guide"](https://cofi.instructure.com/courses/15692/assignments/200729) as a... well... guide. The most helpful feedback will consider the paper from two perspectives: 

    a.   General comments about structure and style. 
    b.   Specific comments about confusing sentences, missing info, etc. For specific comments, please include page number and line or paragraph number. Your comments may be phrased as questions ("What is the implication of XXX being statistically significant?").  Alternatively, you may offer suggestions ("Page 3, paragraph 4: It might clarify what you mean if you explain XXX before this point, rather than waiting until page 5. I found I had to flip between pages to understand your point.") or general comments ("I don’t understand the first sentence of paragraph 5 on page 6.").
6.	Turn in the typed document (["Revising Guide"](https://cofi.instructure.com/courses/15692/assignments/200729) with comments) to the [Stage IV Canvas assignment](https://cofi.instructure.com/courses/15692/assignments/200729) and email it to the author. If you’ve written comments on the physical draft, give that back to the author as well.

## Stage IV.V: Self-review

> When your story is ready for rewrite, cut it to the bone. Get rid of every ounce of excess fat. This is going to hurt; revising a story down to the bare essentials is always a little like murdering children, but it must be done.
—Stephen King

It will be helpful, after having a few days away from your paper, to review it using the ["Revising Guide"](https://cofi.instructure.com/courses/15692/assignments/200729).  Try to look at it with fresh eyes.  Read it aloud. Convince a friend/significant other/family member to listen to you read it.  Encourage them to interrupt you when they don’t understand something or the writing is unclear.  Interrupt yourself when you don’t understand something or the writing is unclear. Make notes to yourself about changes you should make: things you should add or delete from the paper, ways to make it more clear or more concise, etc.  (You may not want to start making those changes until you read the professor and peer feedback.)

## Stage V: Revise

> The time to begin writing an article is when you have finished it to your satisfaction. By that time you begin to clearly and logically perceive what it is you really want to say.
—Mark Twain

1.	Read carefully through the comment documents you received from peers and professor review.  Consider also your self-review.
2.	Make thoughtful, liberal (and possibly painful) changes to your paper. 
3.	Marvel at how much better (and probably shorter) your paper is.
4.	Provide responses to each comment document. For this, I recommend just adding your response under each point-by-point comment in each document.  Make sure your responses are in a different color font than the reviewer’s, so I can tell the different between the reviewer’s comments and your responses.
In some cases, the response may be as simple as "change was made." For others,  (particularly comments you choose to ignore), you may provide context or reasoning. (e.g. "I chose not to include a graph of blah versus blah because of space issues. However, I now comment on the relationship between blah and blah in paragraph 2 of page 4.") 
5.	Submit the following on Canvas by the due date:
    -	the final paper
    -	the Annotated Appendix, as described in the Project Guidelines.  (Even if you have not made any changes to the Appendix, upload it along with the paper.)
    -	the peer feedback you received, with your response to comments included 
    -	the professor feedback you received, with your response to comments included
