---
title: "Project 5: Poster Presentation"
---

:::{.callout-important icon=false}

#### Quick Facts

#### Due Date

**Wednesday, December 10, 2025**

#### Goal

The goal of this assignment is to present your study and results in a clear, concise, and engaging way to your peers.

#### To Turn In

A poster summarizing your Islands project as a PDF file uploaded to Canvas. All members contribute to both writing and design. You can find template on Canvas.
 
:::



The following is from [Passion-Driven Statistics](https://ldierker1.github.io/passiondrivenstatistics/posters.html):

You have conducted a quantitative research project. Now you will learn how to present your results as a research poster and presentation. Posters offer the opportunity to engage with an audience and to meaningfully disseminate your research findings to others.

Learn keys to a successful poster presentation. Consider your audience and frame your research question and results in an understandable and interesting way. Understand you should be brief, use large font size, and incorporate graphics instead of text whenever possible. See how being clear and concise with a logical layout will ensure the viewing experience is intellectually and aesthetically satisfying for your audience. Click [HERE](https://www.youtube.com/watch?v=WpRpCzoumOQ) to a watch the video lesson.

You will create a 3 column, 40" X 36" poster including an introduction, research questions, methods, results, and discussion.

## Presentation Logistics

- Every group member must participate verbally.  
- Your group will present during our scheduled final exam time.
- Slides can be created in any software (PowerPoint, Google Slides, etc.) but must be uploaded to Canvas as a PDF. Templates are available on Canvas.