{
  "hash": "7b97f922aaf13ea93991cd09dfe9f7e7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Categorical Predictors\"\nauthor: \"Prof. Eric Friedlander\"\ndate: \"2024-10-07\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 MAT 212 - Fall 2024 -  Schedule](https://mat212fa24.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  cache: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n\n\n\n\n\n## Announcements & Getting Started\n\n-   Exam Review Wednesday\n-   Exam Friday\n-   Project proposals due Friday!\n    +   Accepted without penalty through Monday 10/14 at 11:59pm\n-   Don't forget about Oral R Quiz!\n    +   Happy to administer over Teams during the break if you'd like...\n\n::: appex\n📋 [AE 12 - P2P Loans](https://mat212fa24.netlify.app/ae/ae-12-categorical-predictors)\n\n- Open up AE 12\n- Complete Exercise 0 if you have time.\n:::\n\n# Categorical predictors\n\n## Topics\n\n-   Understanding categorical predictors\n-   Understand how categorical predictors interact with quantitative predictors\n\n## Computational setup\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ lubridate 1.9.3     ✔ tibble    3.2.1\n✔ purrr     1.0.2     ✔ tidyr     1.3.1\n✔ readr     2.1.5     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ mosaic::count() masks dplyr::count()\n✖ purrr::cross()  masks mosaic::cross()\n✖ mosaic::do()    masks dplyr::do()\n✖ tidyr::expand() masks Matrix::expand()\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\n✖ tidyr::pack()   masks Matrix::pack()\n✖ mosaic::stat()  masks ggplot2::stat()\n✖ mosaic::tally() masks dplyr::tally()\n✖ tidyr::unpack() masks Matrix::unpack()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(ggformula)\nlibrary(mosaic)\nlibrary(broom)\nlibrary(openintro)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nLoading required package: airports\nLoading required package: cherryblossom\nLoading required package: usdata\n\nAttaching package: 'openintro'\n\nThe following object is masked from 'package:mosaic':\n\n    dotPlot\n\nThe following object is masked from 'package:fivethirtyeight':\n\n    drug_use\n\nThe following object is masked from 'package:dslabs':\n\n    murders\n\nThe following objects are masked from 'package:lattice':\n\n    ethanol, lsegments\n```\n\n\n:::\n\n```{.r .cell-code}\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(kableExtra)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n\nAttaching package: 'kableExtra'\n\nThe following object is masked from 'package:dplyr':\n\n    group_rows\n```\n\n\n:::\n\n```{.r .cell-code}\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_bw(base_size = 16))\n```\n:::\n\n\n\n\n\n\n# Data\n\n## Data: Peer-to-peer lender\n\nToday's data is a sample of 50 loans made through a peer-to-peer lending club. The data is in the `loan50` data frame in the **openintro** R package.\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 50 × 3\n   annual_income verified_income interest_rate\n           <dbl> <fct>                   <dbl>\n 1         59000 Not Verified            10.9 \n 2         60000 Not Verified             9.92\n 3         75000 Verified                26.3 \n 4         75000 Not Verified             9.92\n 5        254000 Not Verified             9.43\n 6         67000 Source Verified          9.92\n 7         28800 Source Verified         17.1 \n 8         80000 Not Verified             6.08\n 9         34000 Not Verified             7.97\n10         80000 Source Verified         12.6 \n# ℹ 40 more rows\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Variables\n\n**Predictors**:\n\n::: nonincremental\n-   `annual_income`: Annual income\n-   `verified_income`: Whether borrower's income source and amount have been verified (`Not Verified`, `Source Verified`, `Verified`)\n:::\n\n**Response**: `interest_rate`: Interest rate for the loan\n\n## Response: `interest_rate`\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-categorical-predictors_files/figure-html/unnamed-chunk-3-1.png){fig-align='center' width=3000}\n:::\n:::\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|  min| median|  max|   iqr|\n|----:|------:|----:|-----:|\n| 5.31|   9.93| 26.3| 5.755|\n\n\n:::\n:::\n\n\n\n\n\n\n## Predictors {.small}\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\np1 <- loan50 |> \n  gf_bar(verified_income~.) |> \n  gf_labs(title = \"Verified Income\", \n       y = \"\")\n\np2 <- loan50 |> \n  gf_histogram(~annual_income, binwidth = 20000) |> \n  gf_labs(title = \"\",\n       x = \"Annual income\")\n\np1 / p2\n```\n\n::: {.cell-output-display}\n![](17-categorical-predictors_files/figure-html/unnamed-chunk-5-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n\n\n\n\n## Data manipulation: Rescale income\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nloan50 <- loan50 |>\n  mutate(annual_income_k = annual_income / 1000)\n\nloan50 |> \n  gf_histogram(~annual_income_k, binwidth = 20) |> \n  gf_labs(title = \"Annual income (in $1000s)\", x = \"\")\n```\n\n::: {.cell-output-display}\n![](17-categorical-predictors_files/figure-html/unnamed-chunk-6-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\n\n\n\n# Categorical predictor variables\n\n::: appex\nComplete Exercises 1 and 2.\n:::\n\n\n## Indicator variables\n\n-   Suppose there is a categorical variable with $K$ categories (levels)\n\n-   We can make $K$ indicator variables - one indicator for each category\n\n-   An **indicator variable** takes values 1 or 0\n\n    -   1 if the observation belongs to that category\n    -   0 if the observation does not belong to that category\n\n## Data manipulation: Create indicator variables for `verified_income`\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nloan50 <- loan50 |>\n  mutate(\n    not_verified = if_else(verified_income == \"Not Verified\", 1, 0),\n    source_verified = if_else(verified_income == \"Source Verified\", 1, 0),\n    verified = if_else(verified_income == \"Verified\", 1, 0)\n  )\n\nloan50 |>\n  select(verified_income, not_verified, source_verified, verified) |>\n  slice(1, 3, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  verified_income not_verified source_verified verified\n  <fct>                  <dbl>           <dbl>    <dbl>\n1 Not Verified               1               0        0\n2 Verified                   0               0        1\n3 Source Verified            0               1        0\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Indicators in the model {.smaller}\n\n-   We will use $K-1$ of the indicator variables in the model.\n-   The **reference level** or **baseline** is the category that doesn't have a term in the model.\n-   The coefficients of the indicator variables in the model are interpreted as the expected change in the response compared to the baseline, holding all other variables constant.\n-   This approach is also called **dummy coding** and *R will do this for you*\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nloan50 |>\n  select(verified_income, source_verified, verified) |>\n  slice(1, 3, 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  verified_income source_verified verified\n  <fct>                     <dbl>    <dbl>\n1 Not Verified                  0        0\n2 Verified                      0        1\n3 Source Verified               1        0\n```\n\n\n:::\n:::\n\n\n\n\n\n\n## Application Exercise\n\n::: appex\nComplete Exercises 3 & 4\n:::\n\n## Interpreting `verified_income` {.smaller}\n\n::::{.columns}\n:::{.column}\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term                           | estimate| std.error| statistic| p.value|\n|:------------------------------|--------:|---------:|---------:|-------:|\n|(Intercept)                    |    9.541|     1.006|     9.487|   0.000|\n|verified_incomeSource Verified |    2.224|     1.440|     1.544|   0.129|\n|verified_incomeVerified        |    6.312|     1.836|     3.437|   0.001|\n\n\n:::\n:::\n\n\n\n\n\n:::\n:::{.column}\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-categorical-predictors_files/figure-html/unnamed-chunk-10-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\n\n\n:::\n::::\n\n::: question\n-   Where do we see each of the estimates in the plot?\n-   Where do we see the values we'd predict in the plot?\n-   Are `verified_income` and `interest_rate` **correlated**?\n:::\n\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"countdown\" id=\"timer_d3013392\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">03</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n\n:::\n:::\n\n\n\n\n\n\n\n## Model equation\n\n$$\n\\begin{align}\\hat{\\text{interest_rate}} =  9.541 &+ 2.224 \\times \\text{source_verified}\\\\  \n&+ 6.312 \\times \\text{verified}\n\\end{align}\n$$\n\n# Adding in another predictor\n\n::: appex\nComplete Exercise 5-6.\n:::\n\n## Interest rate vs. annual income: parallel slopes\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-categorical-predictors_files/figure-html/unnamed-chunk-12-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\n\n\n\n## Parallel slopes interpretation {.smaller}\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term                           | estimate| std.error| statistic| p.value|\n|:------------------------------|--------:|---------:|---------:|-------:|\n|(Intercept)                    |   11.388|     1.352|     8.423|   0.000|\n|annual_income_k                |   -0.022|     0.011|    -1.974|   0.054|\n|verified_incomeSource Verified |    2.171|     1.398|     1.553|   0.127|\n|verified_incomeVerified        |    6.792|     1.799|     3.776|   0.000|\n\n\n:::\n:::\n\n\n\n\n\n\n-   Slope of `annual_income_k` is -0.022 regardless of `verified_income` level\n-   Change in `verified_income` corresponds to a shift in the intercept\n    +   Intercept for `Not Verified` is 11.388\n    +   For `Source Verified` shift intercept up 2.171 \n        -   (i.e. intercept $= 11.388 + 2.171 = 13.599$)\n    +   For `Verified` shift intercept up 6.792 **from `Not Verified`**\n        -   (i.e. intercept $= 11.388 + 6.792 = 18.180$)\n\n\n## Interest rate vs. annual income: interaction term\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-categorical-predictors_files/figure-html/unnamed-chunk-14-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\n\n\n\n\n## Interpreting interaction terms {.smaller}\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term                                           | estimate| std.error| statistic| p.value|\n|:----------------------------------------------|--------:|---------:|---------:|-------:|\n|(Intercept)                                    |   10.303|     1.897|     5.432|   0.000|\n|annual_income_k                                |   -0.009|     0.019|    -0.471|   0.640|\n|verified_incomeSource Verified                 |    3.423|     2.534|     1.351|   0.184|\n|verified_incomeVerified                        |    9.788|     3.652|     2.680|   0.010|\n|annual_income_k:verified_incomeSource Verified |   -0.015|     0.026|    -0.591|   0.558|\n|annual_income_k:verified_incomeVerified        |   -0.031|     0.033|    -0.961|   0.342|\n\n\n:::\n:::\n\n\n\n\n\n\n-   Slope of `annual_income_k` **depends** on `verified_income` level\n-   **No difference:** fit three separate linear models on the data corresponding to each level of `verified_income`\n\n## Understanding the model {.midi}\n\n$$\n\\begin{aligned}\n\\hat{interest\\_rate} &= 910.303 - 0.009 \\times annual\\_income\\_k \\\\ &+ 3.423 \\times SourceVerified + 9.788 \\times Verified \\\\ &- 0.015 \\times annual\\_income\\_k \\times SourceVerified\\\\ &- 0.031 \\times annual\\_income\\_k \\times Verified\n\\end{aligned}\n$$\n\n::: appex\nComplete Exercise 7\n:::\n",
    "supporting": [
      "17-categorical-predictors_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.4.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.4.0/countdown.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}