{
  "hash": "cf8eedc5100c06d2e8637375824d8009",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MLR: Inference\"\nauthor: \"Prof. Eric Friedlander\"\nfooter: \"[🔗 MATH 2025 - Fall 2025 - Schedule](https://math2025fa25.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  cache: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib  \n---\n\n\n\n## Application Exercise\n\n::: appex\n📋 AE 15 - Inference for MLR\n\n- Complete Exercises 0-1\n:::\n\n\n## Topics\n\n::: nonincremental\n-   Inference for multiple linear regression\n-   Effect Size and Power\n:::\n\n## Computational setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(mosaic)\nlibrary(Stat2Data)\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(scales)\nlibrary(GGally)\nlibrary(countdown)\nlibrary(rms)\nlibrary(coursekata)\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 16))\n```\n:::\n\n\n\n## Data: `Tadpoles` {.smaller}\n\n::: nonincremental\nBiologists wondered whether tadpoles can adjust the relative length of their intestines if they are exposed to a fungus called Batrachochytrium dendrobatidis (Bd).\n:::\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 27\nColumns: 4\n$ Treatment       <fct> Bd, Bd, Bd, Bd, Bd, Bd, Bd, Bd, Bd, Bd, Bd, Bd, Bd, Bd…\n$ Body            <dbl> 20.28, 19.75, 19.28, 17.81, 20.79, 16.99, 18.12, 16.95…\n$ GutLength       <dbl> 191.40, 142.92, 169.81, 152.18, 171.33, 153.92, 181.08…\n$ MouthpartDamage <dbl> 0.679, 0.607, 0.750, 0.821, 0.696, 0.571, 0.571, 0.571…\n```\n\n\n:::\n:::\n\n\n\nSource: [Stat2Data](https://cran.r-project.org/web/packages/Stat2Data/refman/Stat2Data.html#Tadpoles).\n\n\n\n# Conduct a hypothesis test for $\\beta_j$\n\n## [Review: Simple linear regression (SLR)]{.r-fit-text}\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\np1 <- gf_jitter(GutLength ~ Treatment, data = Tadpoles, alpha = 0.5, height = 0, width = 0.1) |>\n  gf_model(lm(GutLength ~ Treatment, data = Tadpoles), color = \"red\") |>\n  gf_labs(x = \"Treatment\", y = \"Gut Length (mm)\")\np2 <- gf_point(GutLength ~ MouthpartDamage, data = Tadpoles, alpha = 0.5) |>\n  gf_model(lm(GutLength ~ MouthpartDamage, data = Tadpoles), color = \"red\") |>\n  gf_labs(x = \"Mouthpart Damage\", y = \"Gut Length (mm)\")\np1 + p2\n```\n\n::: {.cell-output-display}\n![](15-mlr-inference_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\n\n## SLR model summary\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\ntreatment_model <- lm(GutLength ~ Treatment, data = Tadpoles)\ndamage_model <- lm(GutLength ~ MouthpartDamage, data = Tadpoles)\ntidy(treatment_model) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|term             |  estimate| std.error| statistic|   p.value|\n|:----------------|---------:|---------:|---------:|---------:|\n|(Intercept)      | 168.34714|  7.357157| 22.882092| 0.0000000|\n|TreatmentControl |  33.02824| 10.602792|  3.115051| 0.0045722|\n\n\n:::\n\n```{.r .cell-code  code-fold=\"true\"}\ntidy(damage_model) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|term            |  estimate| std.error| statistic|   p.value|\n|:---------------|---------:|---------:|---------:|---------:|\n|(Intercept)     | 137.57782|  39.07066|  3.521256| 0.0016738|\n|MouthpartDamage |  70.85005|  58.59173|  1.209216| 0.2378918|\n\n\n:::\n:::\n\n\n\n## SLR hypothesis test {.smaller}\n\n1.  **Set hypotheses:** $H_0: \\beta_1 = 0$ vs. $H_A: \\beta_1 \\ne 0$\n\n. . .\n\n2.  **Calculate test statistic and p-value**\n. . .\n\n3.  **State the conclusion**\n\n## Multiple linear regression\n\n- Discussion: How should we handle our confounding variables?\n\n. . .\n\nComplete Exercise 2.\n\n## Multiple linear regression\n\nThe multiple linear regression model assumes $$Y|X_1, X_2,  \\ldots, X_p \\sim N(\\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\dots + \\beta_p X_p, \\sigma_\\epsilon^2)$$\n\n. . .\n\nFor a given observation $(x_{i1}, x_{i2}, \\ldots, x_{ip}, y_i)$, we can rewrite the previous statement as\n\n$$y_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\dots + \\beta_p x_{ip} + \\epsilon_{i}, \\hspace{10mm} \\epsilon_i \\sim N(0,\\sigma_{\\epsilon}^2)$$\n\n\n## Estimating $\\sigma_\\epsilon$ {.smaller}\n\nFor a given observation $(x_{i1}, x_{i2}, \\ldots,x_{ip}, y_i)$ the residual is\n$$\n\\begin{aligned}\ne_i &= y_{i} - \\hat{y_i}\\\\\n&= y_i - (\\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i1} + \\hat{\\beta}_{2} x_{i2} + \\dots + \\hat{\\beta}_p x_{ip})\n\\end{aligned}\n$$\n\n. . .\n\nThe estimated value of the regression standard error , $\\sigma_{\\epsilon}$, is\n\n$$\\hat{\\sigma}_\\epsilon  = \\sqrt{\\frac{\\sum_{i=1}^ne_i^2}{n-p-1}}$$\n\n. . .\n\nAs with SLR, we use $\\hat{\\sigma}_{\\epsilon}$ to calculate $SE_{\\hat{\\beta}_j}$, the standard error of each coefficient. See [Matrix Form of Linear Regression](https://github.com/STA210-Sp19/supplemental-notes/blob/master/regression-basics-matrix.pdf) for more detail.\n\n## MLR Model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(GutLength ~ Treatment + Body, data = Tadpoles) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term             estimate std.error statistic p.value\n  <chr>               <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)         15.5      53.8      0.288 0.776  \n2 TreatmentControl    16.3      11.0      1.48  0.153  \n3 Body                 8.07      2.82     2.86  0.00859\n```\n\n\n:::\n:::\n\n\n## MLR hypothesis test: treatment {.smaller}\n\n1.  **Set hypotheses:** $H_0: \\beta_{trmt} = 0$ vs. $H_A: \\beta_{trmt} \\ne 0$, given other `Body` is in the model\n\n. . .\n\n2.  **Calculate test statistic and p-value:** The test statistic is $t = 1.48$. The p-value is calculated using a $t$ distribution with $$(n - p - 1) = 27-2-1 = 24$$ degrees of freedom. The p-value is $\\approx 0.153$.\n  \n    + Note that $p$ counts all non-intercept $\\beta$'s\n\n. . .\n\n3.  **State the conclusion:** The p-value provides no evidence in favor of the alternative, so we fail to reject $H_0$. The data does not provide evidence that a exposure to the *Bd* fungus is a useful predictor *in a model that already contains body length as a predictor of gut length* (could also say *when controlling for body length*).\n\n\n## MLR hypothesis test: interaction terms {.smaller}\n\n- Framework: Same as previous slide except use $\\beta$ of interaction term\n- $p$ (the number of predictors) should include the interaction term\n- Conclusion: tells you whether interaction term is a useful predictor\n- Warning: if $X_1$ and $X_2$ have an interaction term, don't try to interpret their individual p-values... if interaction term is significant, then both variables are important\n\n::: appex\nComplete Exercises 3.\n:::\n\n# Effect Size and Power\n\n## Overview {.smaller}\n\n-   **Effect Size:** \n    +   General Idea: how big is your parameter compared to the variability of your data\n    +   Why is it important: if parameter has small effect size, it may not be a useful parameter to include. However, what effect size is useful depends on your problem\n    +   In practice: many formal ways of determining effects size which we won't talk about\n\n-   **Statistical Power:** the ability of a hypothesis test to detect a given **effect size**\n    +   more data = more power\n    +   tons of data = tons of power\n    +   In practice: think about how what effect size you'd like to be able to detect and design your study to collect enough data to do so\n\n## Effect Size\n\n-  A few measures of effect size\n  +  Cohen's $d$ (for when you have two groups: e.g. treament vs. control)\n  +  $R^2$ (for when you have continuous predictors)\n-  When evaluating effect size, consider practical significance not just statistical significance\n-  Effect size DOESN'T depend on sample size (other than sampling variability)\n-  Statistical significance DOES depend on sample size\n\n## Power\n\n-   Power: probability of correctly rejecting null hypothesis given a certain effect size\n-   Power depends on:\n    +   Effect size\n    +   Sample size\n    +   Significance level ($\\alpha$)\n    +   Variability in the data\n-   In practice: decide on a minimum effect size you want to be able to detect, then design your study to have enough power to detect that effect size\n\n## Power Analysis using Simulation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlm(GutLength ~ Treatment + Body, data = Tadpoles) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term             estimate std.error statistic p.value\n  <chr>               <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)         15.5      53.8      0.288 0.776  \n2 TreatmentControl    16.3      11.0      1.48  0.153  \n3 Body                 8.07      2.82     2.86  0.00859\n```\n\n\n:::\n:::\n\n\n## Power Analysis using Simulation I\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nset.seed(2025)\nsample_size <- 50\nlm(GutLength ~ Treatment + Body, data = resample(Tadpoles, sample_size)) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term             estimate std.error statistic p.value\n  <chr>               <dbl>     <dbl>     <dbl>   <dbl>\n1 (Intercept)         35.1      42.3      0.831 0.410  \n2 TreatmentControl    16.9       8.04     2.10  0.0407 \n3 Body                 7.24      2.18     3.32  0.00176\n```\n\n\n:::\n:::\n\n\n## Power Analysis using Simulation II\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample_size <- 50\nlm(GutLength ~ Treatment + Body, data = resample(Tadpoles, sample_size)) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 5\n  term             estimate std.error statistic  p.value\n  <chr>               <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)         11.1      34.2      0.326 0.746   \n2 TreatmentControl    27.0       8.14     3.32  0.00174 \n3 Body                 7.59      1.82     4.18  0.000125\n```\n\n\n:::\n:::\n\n\n## Power Analysis using Simulation III\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample_size <- 50\ndo(10) * lm(GutLength ~ Treatment + Body, data = resample(Tadpoles, sample_size)) |>\n  tidy()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 30 × 7\n   term             estimate std.error statistic    p.value  .row .index\n   <chr>               <dbl>     <dbl>     <dbl>      <dbl> <int>  <dbl>\n 1 (Intercept)        24.6       35.1     0.700  0.487          1      1\n 2 TreatmentControl   16.8        8.62    1.94   0.0580         2      1\n 3 Body                7.59       1.85    4.10   0.000165       3      1\n 4 (Intercept)       -15.8       34.4    -0.458  0.649          1      2\n 5 TreatmentControl   -0.741      8.80   -0.0842 0.933          2      2\n 6 Body               10.1        1.83    5.51   0.00000146     3      2\n 7 (Intercept)        21.5       43.6     0.493  0.624          1      3\n 8 TreatmentControl   30.1        8.29    3.63   0.000700       2      3\n 9 Body                7.16       2.33    3.07   0.00357        3      3\n10 (Intercept)        27.1       36.9     0.734  0.467          1      4\n# ℹ 20 more rows\n```\n\n\n:::\n:::\n\n\n## Power Analysis using Simulation IV\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample_size <- 50\ndo(10) * lm(GutLength ~ Treatment + Body, data = resample(Tadpoles, sample_size)) |>\n  tidy() |>\n  filter(term == \"TreatmentControl\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 7\n   term             estimate std.error statistic p.value  .row .index\n   <chr>               <dbl>     <dbl>     <dbl>   <dbl> <int>  <dbl>\n 1 TreatmentControl    10.5       8.31     1.26  0.213       1      1\n 2 TreatmentControl     9.60      6.03     1.59  0.118       1      2\n 3 TreatmentControl    11.6       8.20     1.41  0.164       1      3\n 4 TreatmentControl    16.5       7.24     2.27  0.0276      1      4\n 5 TreatmentControl    22.3       7.36     3.03  0.00399     1      5\n 6 TreatmentControl     2.45      6.63     0.369 0.714       1      6\n 7 TreatmentControl    17.2       8.38     2.06  0.0454      1      7\n 8 TreatmentControl    20.8       8.31     2.51  0.0158      1      8\n 9 TreatmentControl    24.1       7.98     3.02  0.00405     1      9\n10 TreatmentControl    19.4       6.76     2.88  0.00602     1     10\n```\n\n\n:::\n:::\n\n\n## Power Analysis using Simulation IV\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nsample_size <- 50\nsamp_dist <- do(1000) * lm(GutLength ~ Treatment + Body, data = resample(Tadpoles, sample_size)) |>\n  tidy() |>\n  filter(term == \"TreatmentControl\")\n\ntally(samp_dist$p.value < 0.05, format = \"proportion\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nX\n TRUE FALSE \n 0.56  0.44 \n```\n\n\n:::\n:::\n\n\nThe power for a sample of size 50 if we assume the same effect size as in our data is approximately 0.56.\n\nComplete Exercise 4.\n\n# Confidence interval for $\\beta_j$\n\n## Confidence interval for $\\beta_j$ {.midi}\n\n-   The $C\\%$ confidence interval for $\\beta_j$ $$\\hat{\\beta}_j \\pm t^* SE(\\hat{\\beta}_j)$$ where $t^*$ follows a $t$ distribution with $n - p - 1$ degrees of freedom.\n\n-   **Generically**: We are $C\\%$ confident that the interval LB to UB contains the population coefficient of $x_j$.\n\n-   **In context:** We are $C\\%$ confident that for every one unit increase in $x_j$, we expect $y$ to change by LB to UB units, *holding all else constant*.\n\n::: appex\nComplete Exercise 5.\n:::\n\n# Inference pitfalls\n\n## Large sample sizes\n\n::: callout-caution\nIf the sample size is large enough, the test will likely result in rejecting $H_0: \\beta_j = 0$ even $x_j$ has a very small effect on $y$.\n\n::: nonincremental\n-   Consider the **practical significance** of the result not just the statistical significance.\n\n-   Instead of saying **statistically significant** say **statistically detectable**\n\n-   Use confidence intervals to draw conclusions instead of relying only on p-values.\n:::\n:::\n\n## Small sample sizes\n\n::: callout-caution\nIf the sample size is small, there may not be enough evidence to reject $H_0: \\beta_j=0$.\n\n::: nonincremental\n-   When you fail to reject the null hypothesis, **DON'T** immediately conclude that the variable has no association with the response.\n\n-   There may be a linear association that is just not strong enough to detect given your data, or there may be a non-linear association.\n:::\n:::\n\n\n## Recap\n\n- Inference for individual predictors\n    + Hypothesis testing: same as SLR but add *if all other terms are in the model*\n    + Confidence intervals: same as SLR but add *holding all other variables in the model constant*\n- Effect size and power\n    + Effect size: how big is your parameter compared to variability of data\n    + Power: ability to detect a given effect size\n",
    "supporting": [
      "15-mlr-inference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}