{
  "hash": "7fe406b7c0d3ac388bc6fe2390ee1f51",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple Logistic Regression\"\nauthor: \"Prof. Eric Friedlander\"\nfooter: \"[🔗 MAT 212 - Winter 2025 -  Schedule](https://mat212wi25.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  cache: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib  \n---\n\n\n\n\n\n\n\n\n## Topics\n\n-   Extending what we've learned to logistic regression models with multiple predictors\n\n. . .\n \n::: appex\n📋 [AE 12 - Multiple Logistic Regression](/ae/ae-12-multiple-logistic.qmd)\n\n- Complete all of AE 12 using slides as needed.\n:::\n\n\n## Computational setup\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(openintro)\nlibrary(knitr)\nlibrary(kableExtra)  # for table embellishments\nlibrary(Stat2Data)   # for empirical logit\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_bw(base_size = 20))\n```\n:::\n\n\n\n\n# Data\n\n## Risk of coronary heart disease {.midi}\n\nThis data set is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts. We want to examine the relationship between various health characteristics and the risk of having heart disease.\n\n-   `TenYearCHD`:\n\n    -   1: Developed heart disease in next 10 years\n    -   0: Did not develop heart disease in next 10 years\n\n-   `age`: Age at exam time (in years)\n\n-   `education`: 1 = Some High School, 2 = High School or GED, 3 = Some College or Vocational School, 4 = College\n\n## Data prep\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease <- read_csv(\"../data/framingham.csv\") |>\n  select(TenYearCHD, age, education) |>\n  drop_na() |> \n  mutate(education = as.factor(education))\n\nheart_disease |> head() |> kable()\n```\n\n::: {.cell-output-display}\n\n\n| TenYearCHD| age|education |\n|----------:|---:|:---------|\n|          0|  39|4         |\n|          0|  46|2         |\n|          0|  48|1         |\n|          1|  61|3         |\n|          0|  46|3         |\n|          0|  43|2         |\n\n\n:::\n:::\n\n\n\n\n# Coefficient Interpretation\n\n\n## Model output {.midi}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrisk_fit <- glm(TenYearCHD ~ age + education, \n      data = heart_disease, family = \"binomial\")\n\nrisk_fit |> tidy() |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n\n\n\n$$\n\\small{\\log\\Big(\\frac{\\hat{\\pi}}{1-\\hat{\\pi}}\\Big) = -5.385 + 0.073 ~ \\text{age} - 0.242 ~ \\text{ed2} - 0.235 ~ \\text{ed3} - 0.020 ~ \\text{ed4}}\n$$\n\n## Model Interpretation {.smaller}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrisk_fit <- glm(TenYearCHD ~ age + education, \n      data = heart_disease, family = \"binomial\")\n\nrisk_fit |> tidy() |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n\n\n\nAs `age` increases by a year, the typical log-odds of developing coronary heart disease within the next 10 years increases by 0.073 [for patients with the same level of education]{.fragment .highlight-red}.\n\n. . .\n\nAs `age` increases by a year, the typical odds of developing coronary heart disease within the next 10 years increases by a factor of $\\exp(0.073)\\approx 1.08$ (i.e. 8%) [for patients with the same level of education]{.fragment .highlight-red}.\n\n## Model Interpretation {.smaller}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrisk_fit <- glm(TenYearCHD ~ age + education, \n      data = heart_disease, family = \"binomial\")\n\nrisk_fit |> tidy() |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |   -5.385|     0.308|   -17.507|   0.000|\n|age         |    0.073|     0.005|    13.385|   0.000|\n|education2  |   -0.242|     0.112|    -2.162|   0.031|\n|education3  |   -0.235|     0.134|    -1.761|   0.078|\n|education4  |   -0.020|     0.148|    -0.136|   0.892|\n\n\n:::\n:::\n\n\n\n\nPatients [of the same age]{.fragment .highlight-red} who have [a High School diploma or GED/Some College or Vocational School/a College education], the typical log-odds of developing coronary heart disease within the next 10 years is 0.242/0.235/0.020 lower than patients with only some high school.\n\n. . .\n\nPatients [of the same age]{.fragment .highlight-red} who have [a High School diploma or GED/Some College or Vocational School/a College education], the typical odds of developing coronary heart disease within the next 10 years is 79.5%/79.1%/98.0% of the odds for patients with only some high school.\n\n# Inference for a single $\\beta_j$\n\n## Hypothesis test for $\\beta_j$\n\n**Hypotheses:** $H_0: \\beta_j = 0 \\hspace{2mm} \\text{ vs } \\hspace{2mm} H_a: \\beta_j \\neq 0$, [given the other variables in the model]{.fragment .highlight-red}\n\n. . .\n\n**Test Statistic:** $$z = \\frac{\\hat{\\beta}_j - 0}{SE_{\\hat{\\beta}_j}}$$\n\n. . .\n\n**P-value:** $P(|Z| > |z|)$, where $Z \\sim N(0, 1)$, the Standard Normal distribution\n\n## Confidence interval for $\\beta_j$\n\nWe can calculate the **C% confidence interval** for $\\beta_j$ as the following:\n\n$$\n\\Large{\\hat{\\beta}_j \\pm z^* SE_{\\hat{\\beta}_j}}\n$$\n\nwhere $z^*$ is calculated from the $N(0,1)$ distribution\n\n. . .\n\n::: callout-note\nThis is an interval for the change in the log-odds for every one unit increase in $x_j$\n:::\n\n## Interpretation in terms of the odds\n\nThe change in **odds** for every one unit increase in $x_j$.\n\n$$\n\\Large{\\exp\\{\\hat{\\beta}_j \\pm z^* SE_{\\hat{\\beta}_j}\\}}\n$$\n\n. . .\n\n**Interpretation:** We are $C\\%$ confident that for every one unit increase in $x_j$, the odds multiply by a factor of $\\exp\\{\\hat{\\beta}_j - z^* SE_{\\hat{\\beta}_j}\\}$ to $\\exp\\{\\hat{\\beta}_j + z^* SE_{\\hat{\\beta}_j}\\}$, [holding all else constant]{.fragment .highlight-red}.\n\n## Coefficient for `age` {.midi}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -5.385 </td>\n   <td style=\"text-align:right;\"> 0.308 </td>\n   <td style=\"text-align:right;\"> -17.507 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -5.995 </td>\n   <td style=\"text-align:right;\"> -4.788 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(217, 227, 228, 255) !important;\"> age </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.073 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.005 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 13.385 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.063 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.084 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education2 </td>\n   <td style=\"text-align:right;\"> -0.242 </td>\n   <td style=\"text-align:right;\"> 0.112 </td>\n   <td style=\"text-align:right;\"> -2.162 </td>\n   <td style=\"text-align:right;\"> 0.031 </td>\n   <td style=\"text-align:right;\"> -0.463 </td>\n   <td style=\"text-align:right;\"> -0.024 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education3 </td>\n   <td style=\"text-align:right;\"> -0.235 </td>\n   <td style=\"text-align:right;\"> 0.134 </td>\n   <td style=\"text-align:right;\"> -1.761 </td>\n   <td style=\"text-align:right;\"> 0.078 </td>\n   <td style=\"text-align:right;\"> -0.501 </td>\n   <td style=\"text-align:right;\"> 0.023 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education4 </td>\n   <td style=\"text-align:right;\"> -0.020 </td>\n   <td style=\"text-align:right;\"> 0.148 </td>\n   <td style=\"text-align:right;\"> -0.136 </td>\n   <td style=\"text-align:right;\"> 0.892 </td>\n   <td style=\"text-align:right;\"> -0.317 </td>\n   <td style=\"text-align:right;\"> 0.266 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n\n. . .\n\n**Hypotheses:**\n\n$$\nH_0: \\beta_{age} = 0 \\hspace{2mm} \\text{ vs } \\hspace{2mm} H_a: \\beta_{age} \\neq 0\n$$\n[given education is in the model]{.fragment .highlight-red}\n\n## Coefficient for `age` {.midi}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -5.385 </td>\n   <td style=\"text-align:right;\"> 0.308 </td>\n   <td style=\"text-align:right;\"> -17.507 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -5.995 </td>\n   <td style=\"text-align:right;\"> -4.788 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(217, 227, 228, 255) !important;\"> age </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.073 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.005 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 13.385 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.063 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.084 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education2 </td>\n   <td style=\"text-align:right;\"> -0.242 </td>\n   <td style=\"text-align:right;\"> 0.112 </td>\n   <td style=\"text-align:right;\"> -2.162 </td>\n   <td style=\"text-align:right;\"> 0.031 </td>\n   <td style=\"text-align:right;\"> -0.463 </td>\n   <td style=\"text-align:right;\"> -0.024 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education3 </td>\n   <td style=\"text-align:right;\"> -0.235 </td>\n   <td style=\"text-align:right;\"> 0.134 </td>\n   <td style=\"text-align:right;\"> -1.761 </td>\n   <td style=\"text-align:right;\"> 0.078 </td>\n   <td style=\"text-align:right;\"> -0.501 </td>\n   <td style=\"text-align:right;\"> 0.023 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education4 </td>\n   <td style=\"text-align:right;\"> -0.020 </td>\n   <td style=\"text-align:right;\"> 0.148 </td>\n   <td style=\"text-align:right;\"> -0.136 </td>\n   <td style=\"text-align:right;\"> 0.892 </td>\n   <td style=\"text-align:right;\"> -0.317 </td>\n   <td style=\"text-align:right;\"> 0.266 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n\n**Test statistic:**\n\n$$z = \\frac{0.07328 - 0}{0.00547} = 13.39$$\n\n## Coefficient for `age` {.midi}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -5.385 </td>\n   <td style=\"text-align:right;\"> 0.308 </td>\n   <td style=\"text-align:right;\"> -17.507 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -5.995 </td>\n   <td style=\"text-align:right;\"> -4.788 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(217, 227, 228, 255) !important;\"> age </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.073 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.005 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 13.385 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.063 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.084 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education2 </td>\n   <td style=\"text-align:right;\"> -0.242 </td>\n   <td style=\"text-align:right;\"> 0.112 </td>\n   <td style=\"text-align:right;\"> -2.162 </td>\n   <td style=\"text-align:right;\"> 0.031 </td>\n   <td style=\"text-align:right;\"> -0.463 </td>\n   <td style=\"text-align:right;\"> -0.024 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education3 </td>\n   <td style=\"text-align:right;\"> -0.235 </td>\n   <td style=\"text-align:right;\"> 0.134 </td>\n   <td style=\"text-align:right;\"> -1.761 </td>\n   <td style=\"text-align:right;\"> 0.078 </td>\n   <td style=\"text-align:right;\"> -0.501 </td>\n   <td style=\"text-align:right;\"> 0.023 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education4 </td>\n   <td style=\"text-align:right;\"> -0.020 </td>\n   <td style=\"text-align:right;\"> 0.148 </td>\n   <td style=\"text-align:right;\"> -0.136 </td>\n   <td style=\"text-align:right;\"> 0.892 </td>\n   <td style=\"text-align:right;\"> -0.317 </td>\n   <td style=\"text-align:right;\"> 0.266 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n\n**P-value:**\n\n$$\nP(|Z| > |13.39|) \\approx 0\n$$\n\n. . .\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n2 * pnorm(13.64,lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2.315606e-42\n```\n\n\n:::\n:::\n\n\n\n\n## Coefficient for `age` {.midi}\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -5.385 </td>\n   <td style=\"text-align:right;\"> 0.308 </td>\n   <td style=\"text-align:right;\"> -17.507 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -5.995 </td>\n   <td style=\"text-align:right;\"> -4.788 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(217, 227, 228, 255) !important;\"> age </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.073 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.005 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 13.385 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.063 </td>\n   <td style=\"text-align:right;background-color: rgba(217, 227, 228, 255) !important;\"> 0.084 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education2 </td>\n   <td style=\"text-align:right;\"> -0.242 </td>\n   <td style=\"text-align:right;\"> 0.112 </td>\n   <td style=\"text-align:right;\"> -2.162 </td>\n   <td style=\"text-align:right;\"> 0.031 </td>\n   <td style=\"text-align:right;\"> -0.463 </td>\n   <td style=\"text-align:right;\"> -0.024 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education3 </td>\n   <td style=\"text-align:right;\"> -0.235 </td>\n   <td style=\"text-align:right;\"> 0.134 </td>\n   <td style=\"text-align:right;\"> -1.761 </td>\n   <td style=\"text-align:right;\"> 0.078 </td>\n   <td style=\"text-align:right;\"> -0.501 </td>\n   <td style=\"text-align:right;\"> 0.023 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> education4 </td>\n   <td style=\"text-align:right;\"> -0.020 </td>\n   <td style=\"text-align:right;\"> 0.148 </td>\n   <td style=\"text-align:right;\"> -0.136 </td>\n   <td style=\"text-align:right;\"> 0.892 </td>\n   <td style=\"text-align:right;\"> -0.317 </td>\n   <td style=\"text-align:right;\"> 0.266 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n\n**Conclusion:**\n\nThe p-value is very small, so we reject $H_0$. The data provide sufficient evidence that age is a statistically significant predictor of whether someone is will develop heart disease in the next year, [after accounting for education]{.fragment .highlight-red}.\n\n# Comparing Nested Models\n\n## Comparing nested models\n\n-   Suppose there are two models:\n\n    -   Reduced Model includes predictors $x_1, \\ldots, x_q$\n    -   Full Model includes predictors $x_1, \\ldots, x_q, x_{q+1}, \\ldots, x_p$\n\n-   We want to test the hypotheses\n\n    $$\n    \\begin{aligned}\n    H_0&: \\beta_{q+1} = \\dots = \\beta_p = 0 \\\\\n    H_A&: \\text{ at least one }\\beta_j \\text{ is not } 0\n    \\end{aligned}\n    $$\n\n-   To do so, we will use the **Nested Likelihood Ratio test (LRT)**, also known as the **Drop-in-deviance test**,\n\n## Likelihood Ratio test {.smaller}\n\n**Hypotheses:**\n\n$$\n\\begin{aligned}\nH_0&: \\beta_{q+1} = \\dots = \\beta_p = 0 \\\\\nH_A&: \\text{ at least 1 }\\beta_j \\text{ is not } 0\n\\end{aligned}\n$$\n\n. . .\n\n**Test Statistic:** $$G = (-2 \\log L_{reduced}) - (-2 \\log L_{full})$$\n\nor sometimes\n\n**Test Statistic:** $$G = (-2 \\log L_{0}) - (-2 \\log L)$$\n\n. . .\n\n**P-value:** $P(\\chi^2 > G)$, calculated using a $\\chi^2$ distribution [with degrees of freedom equal to the difference in the number of parameters in the full and reduced models]{.fragment .highlight-red}\n\n## $\\chi^2$ distribution\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](12-logistic-multiple_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n\n\n## Should we add `education` to a model with only `age`?\n\nFirst model, reduced:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrisk_fit_reduced <- glm(TenYearCHD ~ age, \n      data = heart_disease, family = \"binomial\")\n```\n:::\n\n\n\n\n<br>\n\n. . .\n\nSecond model, full:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"3\"}\nrisk_fit_full <- glm(TenYearCHD ~ age + education, \n      data = heart_disease, family = \"binomial\")\n```\n:::\n\n\n\n\n## Should we add `education` to the model?\n\nCalculate deviance for each model:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ndev_reduced <- glance(risk_fit_reduced)$deviance\ndev_reduced\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3306.68\n```\n\n\n:::\n\n```{.r .cell-code}\ndev_full <- glance(risk_fit_full)$deviance\ndev_full\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 3300.135\n```\n\n\n:::\n:::\n\n\n\n\n## Should we add `education` to the model?\n\nDrop-in-deviance test statistic:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntest_stat <- dev_reduced - dev_full\ntest_stat\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.544306\n```\n\n\n:::\n:::\n\n\n\n\n## Should we add `education` to the model?\n\nCalculate the p-value using a `pchisq()`, with degrees of freedom equal to the number of new model terms in the second model:\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npchisq(test_stat, 3, lower.tail = FALSE) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.08793145\n```\n\n\n:::\n:::\n\n\n\n\n. . .\n\n**Conclusion:** The p-value is between 0.1 and 0.05 indicating mild but not strong evidence that a model with `education` is a [useful predictor when `age` is already in the model]{.fragment .highlight-red}.\n\n## Drop-in-Deviance test in R {.midi}\n\n-   We can use the **`anova`** function to conduct this test\n\n-   Add **`test = \"Chisq\"`** to conduct the drop-in-deviance test\n\n. . .\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nanova(risk_fit_reduced, risk_fit_full, test = \"Chisq\") |>\n  tidy() |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term                         | df.residual| residual.deviance| df| deviance| p.value|\n|:----------------------------|-----------:|-----------------:|--:|--------:|-------:|\n|TenYearCHD ~ age             |        4133|          3306.680| NA|       NA|      NA|\n|TenYearCHD ~ age + education |        4130|          3300.135|  3|    6.544|   0.088|\n\n\n:::\n:::\n\n\n\n\n\n\n## Recap\n\n-   Today: Simple logistic to Multiple logistic\n    -   Coefficient interpretations\n    -   Wald test interpretations\n    -   LRTs and Drop-in-Deviance tests\n-   Basic idea add \"holding all else constant\"\n-   LRT allows you to compare nested models and requires a degree of free for each extra parameter in the full model\n",
    "supporting": [
      "12-logistic-multiple_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}