{
  "hash": "99717732c2b98816cf51d7153d24a3af",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"MLR: Inference and Conditions\"\nauthor: \"Prof. Eric Friedlander\"\nfooter: \"[🔗 MAT 212 - Winter 2025 -  Schedule](https://mat212wi25.netlify.app/schedule)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs:\n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: false\n    incremental: false \n    chalkboard: true\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  cache: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib  \n---\n\n\n\n\n\n## Application Exercise\n\n::: appex\n📋 [AE 08 - Inference for MLR](/ae/ae-08-mlr-inference.qmd)\n\n- Open up AE 08 and complete Exercises 0-2\n:::\n\n\n## Topics\n\n::: nonincremental\n-   Inference for multiple linear regression\n-   Checking model conditions\n:::\n\n## Computational setup\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(broom)\nlibrary(mosaic)\nlibrary(mosaicData)\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(scales)\nlibrary(GGally)\nlibrary(countdown)\nlibrary(rms)\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 16))\n```\n:::\n\n\n\n\n## Data: `rail_trail` {.smaller}\n\n::: nonincremental\n-   The Pioneer Valley Planning Commission (PVPC) collected data for ninety days from April 5, 2005 to November 15, 2005.\n-   Data collectors set up a laser sensor, with breaks in the laser beam recording when a rail-trail user passed the data collection station.\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 90\nColumns: 7\n$ volume     <dbl> 501, 419, 397, 385, 200, 375, 417, 629, 533, 547, 432, 418,…\n$ hightemp   <dbl> 83, 73, 74, 95, 44, 69, 66, 66, 80, 79, 78, 65, 41, 59, 50,…\n$ avgtemp    <dbl> 66.5, 61.0, 63.0, 78.0, 48.0, 61.5, 52.5, 52.0, 67.5, 62.0,…\n$ season     <chr> \"Summer\", \"Summer\", \"Spring\", \"Summer\", \"Spring\", \"Spring\",…\n$ cloudcover <dbl> 7.6, 6.3, 7.5, 2.6, 10.0, 6.6, 2.4, 0.0, 3.8, 4.1, 8.5, 7.2…\n$ precip     <dbl> 0.00, 0.29, 0.32, 0.00, 0.14, 0.02, 0.00, 0.00, 0.00, 0.00,…\n$ day_type   <chr> \"Weekday\", \"Weekday\", \"Weekday\", \"Weekend\", \"Weekday\", \"Wee…\n```\n\n\n:::\n:::\n\n\n\n\nSource: [Pioneer Valley Planning Commission](http://www.fvgreenway.org/pdfs/Northampton-Bikepath-volume-Counts%20_05_LTA.pdf) via the **mosaicData** package.\n\n## Visualizing the data\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrail_trail |> ggpairs()\n```\n\n::: {.cell-output-display}\n![](08-mlr-inference_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\n\n# Conduct a hypothesis test for $\\beta_j$\n\n## [Review: Simple linear regression (SLR)]{.r-fit-text}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngf_point(volume ~ avgtemp, data = rail_trail, alpha = 0.5) |>\n  gf_lm()  |>\n  gf_labs(x = \"rail_trail avgtemp\", y = \"avgtemp\")\n```\n\n::: {.cell-output-display}\n![](08-mlr-inference_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\n\n\n## SLR model summary\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\navgtemp_slr_fit <- lm(volume ~ avgtemp, data = rail_trail)\n\ntidy(avgtemp_slr_fit) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic|   p.value|\n|:-----------|--------:|---------:|---------:|---------:|\n|(Intercept) | 99.60227| 63.473587|  1.569192| 0.1201920|\n|avgtemp     |  4.80205|  1.084499|  4.427899| 0.0000272|\n\n\n:::\n:::\n\n\n\n\n## SLR hypothesis test {.smaller}\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic|   p.value|\n|:-----------|--------:|---------:|---------:|---------:|\n|(Intercept) | 99.60227| 63.473587|  1.569192| 0.1201920|\n|avgtemp     |  4.80205|  1.084499|  4.427899| 0.0000272|\n\n\n:::\n:::\n\n\n\n1.  **Set hypotheses:** $H_0: \\beta_1 = 0$ vs. $H_A: \\beta_1 \\ne 0$\n\n. . .\n\n2.  **Calculate test statistic and p-value:** The test statistic is $t= 4.43$ . The p-value is calculated using a $t$ distribution with 88 degrees of freedom. The p-value is $2.72\\times 10^{-5}$.\n\n. . .\n\n3.  **State the conclusion:** The p-value is small, so we reject $H_0$. The data provide strong evidence that avgtemp is a helpful predictor for a rail_trail card holder's rail_trail volume, i.e. there is a linear relationship between avgtemp and rail_trail volume.\n\n## Multiple linear regression\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nrail_trail_fit <- lm(volume ~ avgtemp + hightemp, data = rail_trail)\n\ntidy(rail_trail_fit) |> kable()\n```\n\n::: {.cell-output-display}\n\n\n|term        |  estimate| std.error|  statistic|   p.value|\n|:-----------|---------:|---------:|----------:|---------:|\n|(Intercept) |  1.667237| 56.424299|  0.0295482| 0.9764951|\n|avgtemp     | -7.942489|  2.346235| -3.3852060| 0.0010689|\n|hightemp    | 12.056606|  2.041231|  5.9065368| 0.0000001|\n\n\n:::\n:::\n\n\n\n## Multiple linear regression\n\nThe multiple linear regression model assumes $$Y|X_1, X_2,  \\ldots, X_p \\sim N(\\beta_0 + \\beta_1 X_1 + \\beta_2 X_2 + \\dots + \\beta_p X_p, \\sigma_\\epsilon^2)$$\n\n. . .\n\nFor a given observation $(x_{i1}, x_{i2}, \\ldots, x_{ip}, y_i)$, we can rewrite the previous statement as\n\n$$y_i = \\beta_0 + \\beta_1 x_{i1} + \\beta_2 x_{i2} + \\dots + \\beta_p x_{ip} + \\epsilon_{i}, \\hspace{10mm} \\epsilon_i \\sim N(0,\\sigma_{\\epsilon}^2)$$\n\n\n## Estimating $\\sigma_\\epsilon$ {.smaller}\n\nFor a given observation $(x_{i1}, x_{i2}, \\ldots,x_{ip}, y_i)$ the residual is\n$$\n\\begin{aligned}\ne_i &= y_{i} - \\hat{y_i}\\\\\n&= y_i - (\\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i1} + \\hat{\\beta}_{2} x_{i2} + \\dots + \\hat{\\beta}_p x_{ip})\n\\end{aligned}\n$$\n\n. . .\n\nThe estimated value of the regression standard error , $\\sigma_{\\epsilon}$, is\n\n$$\\hat{\\sigma}_\\epsilon  = \\sqrt{\\frac{\\sum_{i=1}^ne_i^2}{n-p-1}}$$\n\n. . .\n\nAs with SLR, we use $\\hat{\\sigma}_{\\epsilon}$ to calculate $SE_{\\hat{\\beta}_j}$, the standard error of each coefficient. See [Matrix Form of Linear Regression](https://github.com/STA210-Sp19/supplemental-notes/blob/master/regression-basics-matrix.pdf) for more detail.\n\n## MLR hypothesis test: avgtemp {.smaller}\n\n1.  **Set hypotheses:** $H_0: \\beta_{avgtemp} = 0$ vs. $H_A: \\beta_{avgtemp} \\ne 0$, given `hightemp` is in the model\n\n. . .\n\n2.  **Calculate test statistic and p-value:** The test statistic is $t = -3.39$. The p-value is calculated using a $t$ distribution with $$(n - p - 1) = 90 - 2 -1 = 87$$ degrees of freedom. The p-value is $\\approx 0.0011$.\n  \n    + Note that $p$ counts all non-intercept $\\beta$'s\n\n. . .\n\n3.  **State the conclusion:** The p-value is small, so we reject $H_0$. The data provides convincing evidence that a avgtemp is a useful predictor *in a model that already contains rail_trail hightemp as a predictor for the rail_trail volume*.\n\n\n## MLR hypothesis test: interaction terms {.smaller}\n\n- Framework: Same as previous slide except use $\\beta$ of interaction term\n- $p$ (the number of predictors) should include the interaction term\n- Conclusion: tells you whether interaction term is a useful predictor\n- Warning: if $X_1$ and $X_2$ have an interaction term, don't try to interpret their individual p-values... if interaction term is significant, then both variables are important\n\n::: appex\nComplete Exercises 3 and 4.\n:::\n\n\n# Confidence interval for $\\beta_j$\n\n## Confidence interval for $\\beta_j$ {.midi}\n\n-   The $C\\%$ confidence interval for $\\beta_j$ $$\\hat{\\beta}_j \\pm t^* SE(\\hat{\\beta}_j)$$ where $t^*$ follows a $t$ distribution with $n - p - 1$ degrees of freedom.\n\n-   **Generically**: We are $C\\%$ confident that the interval LB to UB contains the population coefficient of $x_j$.\n\n-   **In context:** We are $C\\%$ confident that for every one unit increase in $x_j$, we expect $y$ to change by LB to UB units, *holding all else constant*.\n\n::: appex\nComplete Exercise 5.\n:::\n\n## Confidence interval for $\\beta_j$\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-----------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept) |     1.67|     56.42|      0.03|    0.98|  -110.48|    113.82|\n|avgtemp     |    -7.94|      2.35|     -3.39|    0.00|   -12.61|     -3.28|\n|hightemp    |    12.06|      2.04|      5.91|    0.00|     8.00|     16.11|\n\n\n:::\n:::\n\n\n\n\n# Inference pitfalls\n\n## Large sample sizes\n\n::: callout-caution\nIf the sample size is large enough, the test will likely result in rejecting $H_0: \\beta_j = 0$ even $x_j$ has a very small effect on $y$.\n\n::: nonincremental\n-   Consider the **practical significance** of the result not just the statistical significance.\n\n-   Instead of saying **statistically significant** say **statistically detectable**\n\n-   Use confidence intervals to draw conclusions instead of relying only on p-values.\n:::\n:::\n\n## Small sample sizes\n\n::: callout-caution\nIf the sample size is small, there may not be enough evidence to reject $H_0: \\beta_j=0$.\n\n::: nonincremental\n-   When you fail to reject the null hypothesis, **DON'T** immediately conclude that the variable has no association with the response.\n\n-   There may be a linear association that is just not strong enough to detect given your data, or there may be a non-linear association.\n:::\n:::\n\n## Effect Size and Power {.smaller}\n\n-   **Effect Size:** \n    +   General Idea: how big is your parameter compared to the variability of your data\n    +   Why is it important: if parameter has small effect size, it may not be a useful parameter to include. However, what effect size is useful depends on your problem\n    +   In practice: many formal ways of determining effects size which we won't talk about\n\n-   **Statistical Power:** the ability of a hypothesis test to detect a given **effect size**\n    +   more data = more power\n    +   tons of data = tons of power\n    +   In practice: think about how what effect size you'd like to be able to detect and design your study to collect enough data to do so\n\n::: appex\nComplete Exercise 6\n:::\n\n# Conditions for inference\n\n\n## Model conditions\n\nOur model conditions are the same as they were with SLR:\n\n1.  **Linearity:** There is a linear relationship between the response and predictor variables.\n\n2.  **Constant Variance:** The variability about the least squares line is generally constant.\n\n3.  **Normality:** The distribution of the residuals is approximately normal.\n\n4.  **Independence:** The residuals are independent from each other.\n\n\n## Checking Linearity\n\n-   Look at a plot of the residuals vs. predicted values\n\n-   Look at a plot of the residuals vs. each predictor\n\n    +   Use scatter plots for quantitative and boxplots of categorical predictors\n\n-   Linearity is met if there is no discernible pattern in each of these plots\n\nComplete Exercises 7-10\n\n## Fitting the Full Model {.smaller}\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nfull_model <- lm(volume ~ . , data = rail_trail)\nfull_model |> tidy() |>  kable()\n```\n\n::: {.cell-output-display}\n\n\n|term            |   estimate| std.error|  statistic|   p.value|\n|:---------------|----------:|---------:|----------:|---------:|\n|(Intercept)     |  17.622161| 76.582860|  0.2301058| 0.8185826|\n|hightemp        |   7.070528|  2.420523|  2.9210743| 0.0045045|\n|avgtemp         |  -2.036685|  3.142113| -0.6481896| 0.5186733|\n|seasonSpring    |  35.914983| 32.992762|  1.0885716| 0.2795319|\n|seasonSummer    |  24.153571| 52.810486|  0.4573632| 0.6486195|\n|cloudcover      |  -7.251776|  3.843071| -1.8869743| 0.0627025|\n|precip          | -95.696525| 42.573359| -2.2478030| 0.0272735|\n|day_typeWeekend |  35.903750| 22.429056|  1.6007696| 0.1132738|\n\n\n:::\n:::\n\n\n\n## Residuals vs. predicted values\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-mlr-inference_files/figure-revealjs/main_res_pred-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\n::: question\nDoes the constant variance condition appear to be satisfied?\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-mlr-inference_files/figure-revealjs/unnamed-chunk-12-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\n## Checking constant variance\n\n-   The vertical spread of the residuals is not constant across the plot.\n\n-   The constant variance condition is not satisfied.\n\n. . .\n\n::: question\nGiven this conclusion, what might be a next step in the analysis?\n:::\n\n## Residuals vs. each predictor\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-mlr-inference_files/figure-revealjs/unnamed-chunk-13-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\n## Checking linearity\n\n-   The plot of the residuals vs. predicted values looked OK\n\n-   The plots of residuals vs. `hightemp` and `avgtemp` appear to have a parabolic pattern.\n\n-   The linearity condition does not appear to be satisfied given these plots.\n\n. . .\n\n::: question\nGiven this conclusion, what might be a next step in the analysis?\n:::\n\nComplete Exercises 11-12.\n\n## Checking normality\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](08-mlr-inference_files/figure-revealjs/unnamed-chunk-14-1.png){fig-align='center' width=3000}\n:::\n:::\n\n\n\nThe distribution of the residuals is approximately unimodal and symmetric but the qqplot shows that tails are too heavy, so the normality condition is likely not satisfied. The sample size 90 is sufficiently large to relax this condition.\n\n## Checking independence\n\n-   We can often check the independence condition based on the context of the data and how the observations were collected.\n\n-   If the data were collected in a particular order, examine a scatter plot of the residuals versus order in which the data were collected.\n\n-   If there is a grouping variable lurking in the background, check the residuals based on that grouping variable.\n\n## Recap\n\n- Inference for individual predictors\n    + Hypothesis testing: same as SLR but add *if all other terms are in the model*\n    + Confidence intervals: same as SLR but add *holding all other variables in the model constant*\n- Conditions: Same as for SLR\n    + For linearity, also check fitter values vs. each predictor",
    "supporting": [
      "08-mlr-inference_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}